# These are supported funding model platforms

github: [Lumvale]
patreon: lumvale-pdf
open_collective: lumvale-pdf
ko_fi: lumvalepdf
tidelift: npm/@lumvalepdf/core
custom: ["https://lumvale.org/donate"]
