@echo off
echo Installing monorepo dependencies...
call npm install

echo Building Lumvale-PDF Core...
call npm run build:core

echo Building Lumvale-PDF UI...
call npm run build:ui

echo Starting Lumvale-PDF...
call npm run start:ui
pause
